// ============================================================================
// APPLICATION ERROR CODES
// ============================================================================
// Purpose: Standardized error codes for API responses
// Format: MODULE_ERROR_TYPE (e.g., AUTH_INVALID_TOKEN)
// Usage: const { ERROR_CODES } = require('../constants');
// ============================================================================

const ERROR_CODES = {
  // ==================== AUTHENTICATION ERRORS ====================
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  
  // ==================== AUTHORIZATION ERRORS ====================
  AUTHZ_PERMISSION_DENIED: 'AUTHZ_PERMISSION_DENIED',
  AUTHZ_ROLE_NOT_FOUND: 'AUTHZ_ROLE_NOT_FOUND',
  AUTHZ_INSUFFICIENT_PRIVILEGES: 'AUTHZ_INSUFFICIENT_PRIVILEGES',
  
  // ==================== VALIDATION ERRORS ====================
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_INVALID_PHONE: 'VALIDATION_INVALID_PHONE',
  VALIDATION_INVALID_DATE: 'VALIDATION_INVALID_DATE',
  VALIDATION_INVALID_FILE_TYPE: 'VALIDATION_INVALID_FILE_TYPE',
  VALIDATION_FILE_TOO_LARGE: 'VALIDATION_FILE_TOO_LARGE',
  
  // ==================== RESOURCE ERRORS ====================
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_DELETED: 'RESOURCE_DELETED',
  
  // ==================== APPLICANT ERRORS ====================
  APPLICANT_NOT_FOUND: 'APPLICANT_NOT_FOUND',
  APPLICANT_PROFILE_INCOMPLETE: 'APPLICANT_PROFILE_INCOMPLETE',
  APPLICANT_ALREADY_REGISTERED: 'APPLICANT_ALREADY_REGISTERED',
  APPLICANT_DOCUMENTS_MISSING: 'APPLICANT_DOCUMENTS_MISSING',
  
  // ==================== APPLICATION ERRORS ====================
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_SUBMITTED: 'APPLICATION_ALREADY_SUBMITTED',
  APPLICATION_ALREADY_EXISTS: 'APPLICATION_ALREADY_EXISTS',
  APPLICATION_LOCKED: 'APPLICATION_LOCKED',
  APPLICATION_NOT_ELIGIBLE: 'APPLICATION_NOT_ELIGIBLE',
  APPLICATION_DEADLINE_PASSED: 'APPLICATION_DEADLINE_PASSED',
  
  // ==================== POST/JOB ERRORS ====================
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_INACTIVE: 'POST_INACTIVE',
  POST_APPLICATIONS_CLOSED: 'POST_APPLICATIONS_CLOSED',
  
  // ==================== MASTER DATA ERRORS ====================
  DISTRICT_NOT_FOUND: 'DISTRICT_NOT_FOUND',
  TALUKA_NOT_FOUND: 'TALUKA_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  EDUCATION_LEVEL_NOT_FOUND: 'EDUCATION_LEVEL_NOT_FOUND',
  DOCUMENT_TYPE_NOT_FOUND: 'DOCUMENT_TYPE_NOT_FOUND',
  
  // ==================== FILE ERRORS ====================
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  
  // ==================== SYSTEM ERRORS ====================
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

// Error messages for each code (can be used as defaults)
const ERROR_MESSAGES = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.AUTH_INVALID_TOKEN]: 'Invalid or malformed token',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Token has expired, please login again',
  [ERROR_CODES.AUTH_TOKEN_MISSING]: 'Authentication token is required',
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: 'Account is locked due to too many failed attempts',
  [ERROR_CODES.AUTHZ_PERMISSION_DENIED]: 'You do not have permission to perform this action',
  [ERROR_CODES.VALIDATION_FAILED]: 'Request validation failed',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Requested resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.APPLICANT_PROFILE_INCOMPLETE]: 'Please complete your profile before proceeding',
  [ERROR_CODES.APPLICATION_ALREADY_SUBMITTED]: 'Application has already been submitted',
  [ERROR_CODES.APPLICATION_LOCKED]: 'Application is locked and cannot be modified',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests, please try again later',
  [ERROR_CODES.INTERNAL_ERROR]: 'An unexpected error occurred'
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES
};
